# Generated by Django 5.2.6 on 2025-11-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target', '0018_remove_budget_target_main_category_id_and_more'),
        ('trans', '0016_categorization_family_id_trans_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='main_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='target.main_category'),
        ),
    ]
