# Generated by Django 5.2.6 on 2025-12-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accounts_account_number'),
        ('trans', '0017_trans_main_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_header_name', models.CharField(max_length=255, null=True)),
                ('Amount_header_name', models.CharField(max_length=255, null=True)),
                ('Description_header_name', models.CharField(max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
