# Generated by Django 5.2.6 on 2025-12-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0018_file_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_mapping',
            old_name='user_id',
            new_name='account_id',
        ),
    ]
