# Generated by Django 5.2.6 on 2025-12-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accounts_account_number'),
        ('trans', '0019_rename_user_id_file_mapping_account_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_mapping',
            new_name='FileMapping',
        ),
    ]
