# Generated by Django 5.2.6 on 2025-10-31 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_family_token'),
        ('target', '0013_alter_budget_target_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='expectedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Expected_income', models.FloatField(blank=True, null=True)),
                ('family_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('month_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='target.months')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='target.years')),
            ],
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Goal', models.FloatField(blank=True, null=True)),
                ('family_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Saving_target', models.FloatField(blank=True, null=True)),
                ('family_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('month_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='target.months')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='target.years')),
            ],
        ),
    ]
