# Generated by Django 5.2.6 on 2025-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0002_savingtarget_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedincome',
            name='frequency',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
