# Generated by Django 5.2.6 on 2025-11-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_expectedincome_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedincome',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='expectedincome',
            name='year_id',
        ),
        migrations.RemoveField(
            model_name='savingtarget',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='savingtarget',
            name='year_id',
        ),
        migrations.AddField(
            model_name='expectedincome',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expectedincome',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savingtarget',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savingtarget',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
