# Generated by Django 5.2.6 on 2025-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_remove_expectedincome_month_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='Goal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
