# Generated by Django 5.2.6 on 2025-11-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_savinggoal_goal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savinggoal',
            old_name='date',
            new_name='due_date',
        ),
    ]
