# Generated by Django 5.2.6 on 2025-11-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0006_rename_date_savinggoal_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
