# Generated by Django 5.2.6 on 2025-11-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accounts_account_number'),
        ('saving', '0007_savinggoal_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
    ]
