# Generated by Django 5.2.6 on 2025-10-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Token',
            field=models.UUIDField(default=True, unique=True),
        ),
    ]
