# Generated by Django 5.2.6 on 2025-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_name',
        ),
        migrations.AlterField(
            model_name='family',
            name='Token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
