# Generated by Django 5.2.6 on 2025-11-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_family_family_name_alter_family_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemebers',
            name='Token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
