# Generated by Django 5.2.6 on 2025-11-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_familymemebers_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymemebers',
            name='family_id',
        ),
    ]
