# Generated by Django 5.2.6 on 2025-11-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_remove_familymemebers_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemebers',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
    ]
