# Generated by Django 5.2.6 on 2025-11-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_familymemebers_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymemebers',
            name='Token',
        ),
    ]
