# Generated by Django 5.2.6 on 2025-11-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_remove_familymemebers_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemebers',
            name='invitation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
