# Generated by Django 5.2.6 on 2025-11-21 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_familymemebers_invitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitationstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='familymemebers',
            name='invitation_status',
        ),
        migrations.AddField(
            model_name='familymemebers',
            name='invitation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.invitationstatus'),
        ),
    ]
