# Generated by Django 5.2.6 on 2025-11-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0010_invitationstatus_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationstatus',
            name='user_id',
        ),
    ]
