# Generated by Django 5.2.6 on 2025-10-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_account_name_alter_accounts_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
