# Generated by Django 5.2.6 on 2025-10-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounts_family_id_bank_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
