# Generated by Django 5.2.6 on 2025-10-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_balance',
            new_name='Balance',
        ),
        migrations.AddField(
            model_name='accounts',
            name='Starting_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
