# Generated by Django 5.2.6 on 2025-11-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_account_balance_accounts_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Starting_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
