# Generated by Django 5.2.6 on 2025-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_starting_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
