# Generated by Django 5.2.6 on 2025-11-15 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('ZIP_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Marital_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone_number', models.IntegerField(blank=True, null=True)),
                ('Job_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
