# Generated by Django 5.2.6 on 2025-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
